FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

WORKDIR /app
COPY . /app/
ENTRYPOINT ["dotnet", "LZL.dll"]